FROM ubuntu:bionic
ENV TZ=Asia/Shanghai
COPY sources.list /etc/apt/

RUN apt-get update && apt-get install -y tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
